GET http://localhost:9080/PASA/api/categories

###

GET http://localhost:9080/PASA/api/categories/Motoryzacja

###

DELETE http://localhost:9080/PASA/api/categories/Motoryzacja

###

GET http://localhost:9080/PASA/api/ads

###

GET http://localhost:9080/PASA/api/ads/5

### tu

GET http://localhost:9080/PASA/api/categories/Motoryzacja/ads

###

GET http://localhost:9080/PASA/api/categories/Motoryzacja/ads/6

###

GET http://localhost:9080/PASA/api/categories/Motoryzacja/ads/8

###

POST http://localhost:9080/PASA/api/categories
Content-Type: application/json

{
  "name": "Zabawki",
  "description": "Zabawki dla dzieci i nie tylko. "

}

###

GET http://localhost:9080/PASA/api/categories

###

GET http://localhost:9080/PASA/api/categories/Zabawki

###

DELETE http://localhost:9080/PASA/api/categories/Motoryzacja/ads/8

###

GET http://localhost:9080/PASA/api/categories/Motoryzacja/ads

###

POST http://localhost:9080/PASA/api/categories/Zabawki/ads
Content-Type: application/json

{
  "title": "Ogloszenie nowe",
  "description": "Tylko na cele edukacyjne, wcale nie mam zamiaru sprzedać opla."

}

###

GET http://localhost:9080/PASA/api/categories/Zabawki/ads

###
























####
#
#GET http://localhost:9080/PASA/api/users/admin
#
####
#
#GET http://localhost:9080/PASA/api/users
#
####
#
#POST http://localhost:9080/PASA/api/avatars/bezzdjec
#Content-Type: multipart/form-data; boundary=boundary
#
#--boundary
#Content-Disposition: form-data; name="avatar"; filename="do_zamiany.jpg'
#
#< ../../src/main/resources/datastore/avatars/do_zamiany.jpg
#--boundary--
#
####
#
#### to nie pojdzie, bo admin juz ma avatar
#
#POST http://localhost:9080/PASA/api/avatars/admin
#Content-Type: multipart/form-data; boundary=boundary
#
#--boundary
#Content-Disposition: form-data; name="avatar";
#
#< ../../src/main/resources/datastore/avatars/do_zamiany.jpg
#--boundary--
#
#
####
#
#PUT http://localhost:9080/PASA/api/avatars/admin
#Content-Type: multipart/form-data; boundary=boundary
#
#--boundary
#Content-Disposition: form-data; name="avatar"; filename="admin.jpg'
#
#< ../../src/main/resources/datastore/avatars/do_zamiany.jpg
#--boundary--
#
#
####
#
#DELETE http://localhost:9080/PASA/api/avatars/admin